/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.view;

/**
 *
 * @author edd
 */
public class MyBillGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form MyBillGUI
     */
    public MyBillGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listBillPanel = new javax.swing.JPanel();
        dateBillPanel = new javax.swing.JPanel();
        yearCBox = new javax.swing.JComboBox<>();
        monthCBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        billsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBillTable = new javax.swing.JTable();
        printBtn = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Listar Facturas");

        dateBillPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar"));

        yearCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));

        monthCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes" }));

        jButton1.setText("Filtrar");

        javax.swing.GroupLayout dateBillPanelLayout = new javax.swing.GroupLayout(dateBillPanel);
        dateBillPanel.setLayout(dateBillPanelLayout);
        dateBillPanelLayout.setHorizontalGroup(
            dateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateBillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(monthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        dateBillPanelLayout.setVerticalGroup(
            dateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateBillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dateBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        billsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        listBillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listBillTable);

        printBtn.setText("Imprimir");

        javax.swing.GroupLayout billsPanelLayout = new javax.swing.GroupLayout(billsPanel);
        billsPanel.setLayout(billsPanelLayout);
        billsPanelLayout.setHorizontalGroup(
            billsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(billsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        billsPanelLayout.setVerticalGroup(
            billsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printBtn)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout listBillPanelLayout = new javax.swing.GroupLayout(listBillPanel);
        listBillPanel.setLayout(listBillPanelLayout);
        listBillPanelLayout.setHorizontalGroup(
            listBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listBillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(billsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateBillPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        listBillPanelLayout.setVerticalGroup(
            listBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listBillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateBillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listBillPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listBillPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billsPanel;
    private javax.swing.JPanel dateBillPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listBillPanel;
    private javax.swing.JTable listBillTable;
    private javax.swing.JComboBox<String> monthCBox;
    private javax.swing.JButton printBtn;
    private javax.swing.JComboBox<String> yearCBox;
    // End of variables declaration//GEN-END:variables
}
