/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.view;

import ec.edu.ups.conectionDB.ConnectionJava;
import ec.edu.ups.controller.CustomerController;
import ec.edu.ups.controller.EmployeeController;
import ec.edu.ups.controller.PrivilegeController;
import ec.edu.ups.controller.UserController;
import ec.edu.ups.model.Customer;
import ec.edu.ups.model.Employee;
import ec.edu.ups.model.Phone;
import ec.edu.ups.model.Privilege;
import ec.edu.ups.services.Services;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edd
 */
public class UserManagementGUI extends JInternalFrame {

    private List<Phone> phones;
    private List<Privilege> pri;
            
    private String pass;
    
    private CustomerController conCus;
    private EmployeeController conEmp;
    
    private ConnectionJava connection;
    
    /**
     * Creates new form UserGUI
     */
    public UserManagementGUI(ConnectionJava connection) {
        initComponents();
        this.connection = connection;
        
        conCus = new CustomerController();
        conEmp = new EmployeeController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usersBtnGroup = new javax.swing.ButtonGroup();
        userPanel = new javax.swing.JPanel();
        dniLB = new javax.swing.JLabel();
        nameLB = new javax.swing.JLabel();
        lastNameLB = new javax.swing.JLabel();
        directionLB = new javax.swing.JLabel();
        directionWLB = new javax.swing.JLabel();
        birthdayLB = new javax.swing.JLabel();
        usernameLB = new javax.swing.JLabel();
        emailLB = new javax.swing.JLabel();
        privilegeLB = new javax.swing.JLabel();
        directionWTxt = new javax.swing.JTextField();
        directionTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        dniTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        createUserBtn = new javax.swing.JButton();
        deleteUserBtn = new javax.swing.JButton();
        privilegeCB = new javax.swing.JComboBox<>();
        phonePanel = new javax.swing.JPanel();
        phoneLb = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        typePhoneCB = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        phonesTable = new javax.swing.JTable();
        createPhoneBtn = new javax.swing.JButton();
        deletePhoneBtn = new javax.swing.JButton();
        updatePhoneBtn = new javax.swing.JButton();
        generateBtn = new javax.swing.JButton();
        userBoxPanel = new javax.swing.JPanel();
        adminBtn = new javax.swing.JRadioButton();
        employeeBtn = new javax.swing.JRadioButton();
        customerBtn = new javax.swing.JRadioButton();
        fechaTxt = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestión Usuarios");

        userPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        dniLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dniLB.setText("Cédula:");

        nameLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLB.setText("Nombre:");

        lastNameLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastNameLB.setText("Apellido:");

        directionLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        directionLB.setText("Dirección:");

        directionWLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        directionWLB.setText("D. Trabajo:");

        birthdayLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        birthdayLB.setText("Fecha Nacimiento:");

        usernameLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameLB.setText("Nombre de Usuario:");

        emailLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLB.setText("Email:");

        privilegeLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        privilegeLB.setText("Privilegio:");

        directionWTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directionWTxtActionPerformed(evt);
            }
        });

        directionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directionTxtActionPerformed(evt);
            }
        });

        lastNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTxtActionPerformed(evt);
            }
        });

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        dniTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTxtActionPerformed(evt);
            }
        });

        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        createUserBtn.setText("Crear");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        deleteUserBtn.setText("Eliminar");
        deleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnActionPerformed(evt);
            }
        });

        privilegeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bajo", "Medio", "Alto" }));

        phonePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Teléfonos"));

        phoneLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phoneLb.setText("Número:");

        phoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtActionPerformed(evt);
            }
        });

        typePhoneCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Móvil", "Convencional" }));

        phonesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(phonesTable);

        createPhoneBtn.setText("Crear");
        createPhoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPhoneBtnActionPerformed(evt);
            }
        });

        deletePhoneBtn.setText("Eliminar");
        deletePhoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePhoneBtnActionPerformed(evt);
            }
        });

        updatePhoneBtn.setText("Editar");
        updatePhoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePhoneBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout phonePanelLayout = new javax.swing.GroupLayout(phonePanel);
        phonePanel.setLayout(phonePanelLayout);
        phonePanelLayout.setHorizontalGroup(
            phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phonePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(phonePanelLayout.createSequentialGroup()
                        .addComponent(createPhoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updatePhoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletePhoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(phonePanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(phonePanelLayout.createSequentialGroup()
                                .addComponent(phoneLb)
                                .addGap(18, 18, 18)
                                .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(typePhoneCB, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        phonePanelLayout.setVerticalGroup(
            phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phonePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLb, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(typePhoneCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createPhoneBtn)
                    .addComponent(updatePhoneBtn)
                    .addComponent(deletePhoneBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(phonePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        generateBtn.setText("Generar Contraseña");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        usersBtnGroup.add(adminBtn);
        adminBtn.setText("Administrador");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });

        usersBtnGroup.add(employeeBtn);
        employeeBtn.setText("Empleado");
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });

        usersBtnGroup.add(customerBtn);
        customerBtn.setText("Cliente");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userBoxPanelLayout = new javax.swing.GroupLayout(userBoxPanel);
        userBoxPanel.setLayout(userBoxPanelLayout);
        userBoxPanelLayout.setHorizontalGroup(
            userBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userBoxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminBtn)
                .addGap(18, 18, 18)
                .addComponent(employeeBtn)
                .addGap(18, 18, 18)
                .addComponent(customerBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userBoxPanelLayout.setVerticalGroup(
            userBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userBoxPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(userBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminBtn)
                    .addComponent(employeeBtn)
                    .addComponent(customerBtn))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        fechaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                                .addComponent(createUserBtn)
                                .addGap(40, 40, 40)
                                .addComponent(deleteUserBtn)
                                .addGap(99, 99, 99))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userPanelLayout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(directionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(directionWTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(userBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phonePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(privilegeLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(usernameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(privilegeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(121, 121, 121)
                                .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(birthdayLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dniLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(directionLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(directionWLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addComponent(userBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLB)
                    .addComponent(usernameLB)
                    .addComponent(dniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLB)
                    .addComponent(nameLB)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLB)
                    .addComponent(privilegeLB)
                    .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(privilegeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(directionLB)
                            .addComponent(directionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(directionWLB)
                            .addComponent(directionWTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(birthdayLB)
                            .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createUserBtn)
                            .addComponent(deleteUserBtn)))
                    .addComponent(phonePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(userPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        this.privilegeCB.setEnabled(false);
        this.directionWTxt.setEditable(false);
    }//GEN-LAST:event_adminBtnActionPerformed

    private void updatePhoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePhoneBtnActionPerformed
         int index = this.phonesTable.getSelectedRow();
            
            Phone phone;
            
            switch(evt.getActionCommand()){
                case "Editar":
                    

                    if (index < 0) {
                        JOptionPane.showMessageDialog(null, "Seleccione un teléfono.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        throw new NullPointerException();
                    }

                    phone = this.phones.get(index);

                    this.phoneTxt.setText(phone.getPhoNumber());

                    if (phone.getPhoType().equals("M")) {

                        this.typePhoneCB.setSelectedItem("Móvil");
                    }else{
                        this.typePhoneCB.setSelectedItem("Fijo");
                    }

                    this.updatePhoneBtn.setActionCommand("Aceptar");
                    this.updatePhoneBtn.setText("Aceptar");
                    break;
                case "Aceptar":
                    phone = new Phone();
                    phone.setPhoNumber(this.phoneTxt.getText());

                    switch(this.typePhoneCB.getSelectedItem().toString()){
                        case "Móvil":
                            phone.setPhoType("M");
                            break;
                        case "Fijo":
                            phone.setPhoType("F");
                            break;
                    }
                    
                    phone.setPhoId(this.phones.get(index).getPhoId());
                    
                    this.phones.set(index, phone);
                    
                    listPhones();
                    
                    this.updatePhoneBtn.setActionCommand("Editar");
                    this.updatePhoneBtn.setText("Editar");
                    break;
                    
            }
                    
                    
    }//GEN-LAST:event_updatePhoneBtnActionPerformed

    private void deletePhoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePhoneBtnActionPerformed
        int index = this.phonesTable.getSelectedRow();
        
        if (index < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un teléfono.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            throw new NullPointerException();
        }
        
        this.phones.remove(index);
        listPhones();
    }//GEN-LAST:event_deletePhoneBtnActionPerformed

    private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtActionPerformed

    private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtnActionPerformed
        UserController conUse = new UserController();
        
        try{
        conUse.delete(connection, this.usernameTxt.getText());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al eliminar." + e.toString());
        }
        
    }//GEN-LAST:event_deleteUserBtnActionPerformed

    private void dniTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void lastNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTxtActionPerformed

    private void directionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directionTxtActionPerformed

    private void directionWTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionWTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directionWTxtActionPerformed

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void fechaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTxtActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        this.privilegeCB.setEnabled(false);
        this.directionWTxt.setEditable(false);
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        this.privilegeCB.setEnabled(true);
        this.directionWTxt.setEditable(true);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        try{
        if (this.employeeBtn.isSelected()) {
            Employee employee = new Employee();
            employee.setUseDNI(this.dniTxt.getText());
            employee.setUseName(this.nameTxt.getText());
            employee.setUseLastNamel(this.lastNameTxt.getText());
            employee.setUseAddress(this.directionTxt.getText());
            employee.setUseUsername(this.usernameTxt.getText());
            employee.setUseEmail(this.emailTxt.getText());
            employee.setUsePassword(this.pass);
            employee.setUsePhones(phones);
            employee.setUseType('E');
            
            Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(this.fechaTxt.getText()); 
            
            employee.setUseBirthDay(date1);
            
            this.conEmp.createEmployee(connection, employee);
        }
        
        if (this.adminBtn.isSelected()) {
            Employee employee = new Employee();
            employee.setUseDNI(this.dniTxt.getText());
            employee.setUseName(this.nameTxt.getText());
            employee.setUseLastNamel(this.lastNameTxt.getText());
            employee.setUseAddress(this.directionTxt.getText());
            employee.setUseUsername(this.usernameTxt.getText());
            employee.setUseEmail(this.emailTxt.getText());
            employee.setUsePassword(this.pass);
            employee.setUsePhones(phones);
            employee.setUseType('A');
            
            this.conEmp.createEmployee(connection, employee);
        }
        
        if (this.customerBtn.isSelected()) {
            Customer customer = new Customer();
            customer.setUseDNI(this.dniTxt.getText());
            customer.setUseName(this.nameTxt.getText());
            customer.setUseLastNamel(this.lastNameTxt.getText());
            customer.setUseAddress(this.directionTxt.getText());
            customer.setUseUsername(this.usernameTxt.getText());
            customer.setUseEmail(this.emailTxt.getText());
            customer.setUsePassword(this.pass);
            customer.setUsePhones(phones);
            customer.setUseWorkAdd(this.directionWTxt.getText());
            
            customer.setUseType('C');
            
            
            int index = this.privilegeCB.getSelectedIndex();
            
            customer.setUsePrivilege(this.pri.get(index));
            
            this.conCus.createCustomer(connection, customer);
        }
        }catch (Exception e){
            System.out.println("EROR " + e.toString());
        }
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void createPhoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPhoneBtnActionPerformed
        
        Phone phone = new Phone();
            phone.setPhoNumber(this.phoneTxt.getText());

            switch(this.typePhoneCB.getSelectedItem().toString()){
                case "Móvil":
                    phone.setPhoType("M");
                    break;
                case "Fijo":
                    phone.setPhoType("F");
                    break;
            }
        
            if (this.phones == null) {
                this.phones = new ArrayList<>();
            }

            this.phones.add(phone);
            listPhones();
        
        
    }//GEN-LAST:event_createPhoneBtnActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        
        try{
        if (this.usernameTxt.getText().equals("")) {
            throw new NullPointerException();
        }
        Services ser = new Services();
        this.pass = ser.getMd5(this.usernameTxt.getText());
        JOptionPane.showMessageDialog(null, "Se generó la contraseña.");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un usuario.");
        }
    }//GEN-LAST:event_generateBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminBtn;
    private javax.swing.JLabel birthdayLB;
    private javax.swing.JButton createPhoneBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JRadioButton customerBtn;
    private javax.swing.JButton deletePhoneBtn;
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JLabel directionLB;
    private javax.swing.JTextField directionTxt;
    private javax.swing.JLabel directionWLB;
    private javax.swing.JTextField directionWTxt;
    private javax.swing.JLabel dniLB;
    private javax.swing.JTextField dniTxt;
    private javax.swing.JLabel emailLB;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JRadioButton employeeBtn;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JButton generateBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNameLB;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JLabel nameLB;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel phoneLb;
    private javax.swing.JPanel phonePanel;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTable phonesTable;
    private javax.swing.JComboBox<String> privilegeCB;
    private javax.swing.JLabel privilegeLB;
    private javax.swing.JComboBox typePhoneCB;
    private javax.swing.JButton updatePhoneBtn;
    private javax.swing.JPanel userBoxPanel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel usernameLB;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.ButtonGroup usersBtnGroup;
    // End of variables declaration//GEN-END:variables

    private void listPhones(){
     DefaultTableModel tableModel = new DefaultTableModel();
        
        String [] colums = {"Número", "Tipo"}; 
        String [][] rows;
        
        int n = this.phones.size();
        
        rows = new String[n][2];
        
        for (int i = 0; i < n; i++) {
            rows[i][0] = this.phones.get(i).getPhoType();
            rows[i][1] = this.phones.get(i).getPhoNumber();
        }
        
        tableModel.setDataVector(rows, colums);
        this.phonesTable.setModel(tableModel);
    }
    
    private void privi(){
        PrivilegeController pri = new PrivilegeController();
        
        this.pri = new ArrayList<>();
        
        pri.getPrivileges(connection, this.pri);
        
        this.privilegeCB.removeAllItems();
        
        for (Privilege p: this.pri) {
            this.privilegeCB.addItem(p.getPriName());
        }
        
    }
    
}
