/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.view;

import ec.edu.ups.conectionDB.ConnectionJava;
import ec.edu.ups.controller.BrandController;
import ec.edu.ups.controller.CityController;
import ec.edu.ups.controller.ModelController;
import ec.edu.ups.controller.OfficeController;
import ec.edu.ups.controller.ProvinceController;
import ec.edu.ups.controller.VehCategoryController;
import ec.edu.ups.controller.VehicleController;
import ec.edu.ups.model.Brand;
import ec.edu.ups.model.City;
import ec.edu.ups.model.Model;
import ec.edu.ups.model.Office;
import ec.edu.ups.model.Province;
import ec.edu.ups.model.VehCategory;
import ec.edu.ups.model.Vehicle;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author edd
 */
public class VehicleGUI extends javax.swing.JInternalFrame {
    
    private BrandController conBrand;
    private ModelController conModel;
    private ProvinceController conProvince;
    private CityController conCity;
    private VehCategoryController conCategory;
    private OfficeController conOffice;
    private VehicleController conVehicle;
    
    private List<Brand> brands;
    private List<Model> models;
    private List<Province> provinces;
    private List<Office> offices;
    private List<City> cities;
    private List<VehCategory> vehCategories;
    
    private Vehicle vehicle;
    
    
    private ConnectionJava connection;

    /**
     * Creates new form VehicleGUI
     */
    public VehicleGUI(ConnectionJava connection) {
        initComponents();
        this.conBrand = new BrandController();
        this.conModel = new ModelController();
        this.conCity = new CityController();
        this.conCategory = new VehCategoryController();
        this.conProvince = new ProvinceController();
        this.conOffice = new OfficeController();
        this.conVehicle = new VehicleController();
        this.connection = connection;
        
        loadComboBox(connection);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehiclePanel = new javax.swing.JPanel();
        detailVehiclePanel = new javax.swing.JPanel();
        plateLB = new javax.swing.JLabel();
        colourLB = new javax.swing.JLabel();
        statusLB = new javax.swing.JLabel();
        kilometrageLB = new javax.swing.JLabel();
        KilometrageTxt = new javax.swing.JTextField();
        statusTxt = new javax.swing.JTextField();
        colourTxt = new javax.swing.JTextField();
        plateTxt = new javax.swing.JTextField();
        categoryLB = new javax.swing.JLabel();
        insuranceNumberTxt = new javax.swing.JTextField();
        createVehicleBtn = new javax.swing.JButton();
        searchVehicleBtn = new javax.swing.JButton();
        editVehicleBtn = new javax.swing.JButton();
        deleteVehicleBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        insuranceNumberLB = new javax.swing.JLabel();
        categoryCBox = new javax.swing.JComboBox<>();
        insuranceDateLB = new javax.swing.JLabel();
        dateText = new javax.swing.JTextField();
        locationPanel = new javax.swing.JPanel();
        brandCBox = new javax.swing.JComboBox<>();
        modelCBox = new javax.swing.JComboBox<>();
        provinceCBox = new javax.swing.JComboBox<>();
        cityCBox = new javax.swing.JComboBox<>();
        oficeCBox = new javax.swing.JComboBox<>();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestión Vehículo");

        vehiclePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehículo"));

        detailVehiclePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        plateLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        plateLB.setText("Placa:");
        plateLB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        colourLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        colourLB.setText("Color:");
        colourLB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        statusLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statusLB.setText("Estado:");

        kilometrageLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kilometrageLB.setText("Kilometraje:");

        categoryLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoryLB.setText("Categoría:");

        createVehicleBtn.setText("Crear");
        createVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVehicleBtnActionPerformed(evt);
            }
        });

        searchVehicleBtn.setText("Buscar");
        searchVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVehicleBtnActionPerformed(evt);
            }
        });

        editVehicleBtn.setText("Editar");
        editVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVehicleBtnActionPerformed(evt);
            }
        });

        deleteVehicleBtn.setText("Eliminar");
        deleteVehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVehicleBtnActionPerformed(evt);
            }
        });

        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(vehicleTable);

        insuranceNumberLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        insuranceNumberLB.setText("Código Seguro:");

        insuranceDateLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        insuranceDateLB.setText("Fecha Seguro:");

        javax.swing.GroupLayout detailVehiclePanelLayout = new javax.swing.GroupLayout(detailVehiclePanel);
        detailVehiclePanel.setLayout(detailVehiclePanelLayout);
        detailVehiclePanelLayout.setHorizontalGroup(
            detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                                    .addComponent(categoryLB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(categoryCBox, 0, 175, Short.MAX_VALUE))
                                .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                                    .addComponent(plateLB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(plateTxt))
                                .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                                    .addComponent(kilometrageLB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(KilometrageTxt))
                                .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                                    .addComponent(statusLB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(statusTxt))
                                .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                                    .addComponent(colourLB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(colourTxt))))
                        .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(insuranceNumberLB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(insuranceNumberTxt))
                        .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(insuranceDateLB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(dateText)))
                    .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createVehicleBtn)
                        .addGap(18, 18, 18)
                        .addComponent(searchVehicleBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editVehicleBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteVehicleBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        detailVehiclePanelLayout.setVerticalGroup(
            detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                        .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(plateLB))
                            .addComponent(plateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(colourLB))
                            .addComponent(colourTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(statusLB))
                            .addComponent(statusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailVehiclePanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(kilometrageLB))
                            .addComponent(KilometrageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryLB)
                            .addComponent(categoryCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insuranceNumberLB)
                            .addComponent(insuranceNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insuranceDateLB)
                            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createVehicleBtn)
                            .addGroup(detailVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deleteVehicleBtn)
                                .addComponent(editVehicleBtn)
                                .addComponent(searchVehicleBtn))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        locationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        brandCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marca" }));
        brandCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandCBoxActionPerformed(evt);
            }
        });

        modelCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modelo" }));

        provinceCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provincia" }));
        provinceCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceCBoxActionPerformed(evt);
            }
        });

        cityCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudad" }));
        cityCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityCBoxActionPerformed(evt);
            }
        });

        oficeCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oficina" }));

        javax.swing.GroupLayout locationPanelLayout = new javax.swing.GroupLayout(locationPanel);
        locationPanel.setLayout(locationPanelLayout);
        locationPanelLayout.setHorizontalGroup(
            locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brandCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modelCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(provinceCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cityCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oficeCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        locationPanelLayout.setVerticalGroup(
            locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(locationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provinceCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oficeCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout vehiclePanelLayout = new javax.swing.GroupLayout(vehiclePanel);
        vehiclePanel.setLayout(vehiclePanelLayout);
        vehiclePanelLayout.setHorizontalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(locationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailVehiclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vehiclePanelLayout.setVerticalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(locationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailVehiclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vehiclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vehiclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brandCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandCBoxActionPerformed
        int index = this.brandCBox.getSelectedIndex();
        
        this.models = new ArrayList<>();
        
        this.conModel.getModels(connection, models, this.brands.get(index - 1));
        
        System.out.println(this.brands.get(index).getBraName());
        
        for (Model m:models) {
            this.modelCBox.addItem(m.getModName());
        }
        
    }//GEN-LAST:event_brandCBoxActionPerformed

    private void createVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVehicleBtnActionPerformed
        // TODO add your handling code here:
        
        //CREAR
        Vehicle vehicle = new Vehicle();
        
        vehicle.setVehPlate(this.plateTxt.getText());
        vehicle.setVehColor(this.colourTxt.getText());
        vehicle.setVehStatus(this.statusTxt.getText().charAt(0));
        vehicle.setVehKilometraje(Double.parseDouble(this.KilometrageTxt.getText()));
        vehicle.setVehInsurranceNumber(this.insuranceNumberTxt.getText());
        
        String pattern = "dd-MM-yyyy";
        SimpleDateFormat dateF = new SimpleDateFormat(pattern);
        Date dateI = null;
        
        String date = this.dateText.getText();
        
        try {
            dateI = dateF.parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(VehicleGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        vehicle.setVehInsurranceDate(dateI);
        vehicle.setVehInsurranceExpires(dateI);
        
        vehicle.setVehOrigin('N');
        
        // Fin
        this.conVehicle.createVehicle(connection, vehicle, 
                this.oficeCBox.getSelectedIndex(), 
                this.modelCBox.getSelectedIndex(), 
                this.categoryCBox.getSelectedIndex(), 
                this.provinceCBox.getSelectedIndex());
        
    }//GEN-LAST:event_createVehicleBtnActionPerformed

    private void searchVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVehicleBtnActionPerformed
        // TODO add your handling code here:
        
        // BUSCAR
        
        this.vehicle = new Vehicle();
        
        this.vehicle.setVehPlate(this.plateTxt.getText());
        
        
        this.conVehicle.readVehicle(connection, vehicle, vehicle.getVehPlate());
        
        this.plateTxt.setText(vehicle.getVehPlate());
        this.colourTxt.setText(vehicle.getVehColor());
        this.statusTxt.setText(""+vehicle.getVehStatus());
        this.KilometrageTxt.setText(""+vehicle.getVehKilometraje());
        this.insuranceNumberTxt.setText(vehicle.getVehInsurranceNumber());
        
        
        
    }//GEN-LAST:event_searchVehicleBtnActionPerformed

    private void editVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVehicleBtnActionPerformed
        // TODO add your handling code here:
        
        //EDITAR
        Vehicle vehicle = new Vehicle();
        
        vehicle.setVehPlate(this.plateTxt.getText());
        vehicle.setVehColor(this.colourTxt.getText());
        vehicle.setVehStatus(this.statusTxt.getText().charAt(0));
        vehicle.setVehKilometraje(Double.parseDouble(this.KilometrageTxt.getText()));
        vehicle.setVehInsurranceNumber(this.insuranceNumberTxt.getText());
        
        
        //
        this.conVehicle.updateVehicle(connection, vehicle, 
                this.oficeCBox.getSelectedIndex());
    }//GEN-LAST:event_editVehicleBtnActionPerformed

    private void deleteVehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVehicleBtnActionPerformed
        // TODO add your handling code here:
        
        //ELIMINAR
        this.conVehicle.deleteVehicle(connection, this.plateTxt.getText());
        
    }//GEN-LAST:event_deleteVehicleBtnActionPerformed

    private void provinceCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceCBoxActionPerformed
        // TODO add your handling code here:
        int index = this.provinceCBox.getSelectedIndex();
        
        this.cities = new ArrayList<>();
        
        this.conCity.getCities(connection, cities, this.provinces.get(index - 1));
        
        //System.out.println(this.brands.get(index).getBraName());
        
        for (City c:cities) {
            this.cityCBox.addItem(c.getCitName());
        }
    }//GEN-LAST:event_provinceCBoxActionPerformed

    private void cityCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityCBoxActionPerformed
        // TODO add your handling code here:
        int index = this.cityCBox.getSelectedIndex();
        
        this.offices = new ArrayList<>();
        
        this.conOffice.getOffices(connection, offices, index);
        
        //System.out.println(this.brands.get(index).getBraName());
        
        for (Office o:offices) {
            this.oficeCBox.addItem(o.getOffMainSt()+" "+o.getOffSideSt());
        }
    }//GEN-LAST:event_cityCBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KilometrageTxt;
    private javax.swing.JComboBox<String> brandCBox;
    private javax.swing.JComboBox<String> categoryCBox;
    private javax.swing.JLabel categoryLB;
    private javax.swing.JComboBox<String> cityCBox;
    private javax.swing.JLabel colourLB;
    private javax.swing.JTextField colourTxt;
    private javax.swing.JButton createVehicleBtn;
    private javax.swing.JTextField dateText;
    private javax.swing.JButton deleteVehicleBtn;
    private javax.swing.JPanel detailVehiclePanel;
    private javax.swing.JButton editVehicleBtn;
    private javax.swing.JLabel insuranceDateLB;
    private javax.swing.JLabel insuranceNumberLB;
    private javax.swing.JTextField insuranceNumberTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kilometrageLB;
    private javax.swing.JPanel locationPanel;
    private javax.swing.JComboBox<String> modelCBox;
    private javax.swing.JComboBox<String> oficeCBox;
    private javax.swing.JLabel plateLB;
    private javax.swing.JTextField plateTxt;
    private javax.swing.JComboBox<String> provinceCBox;
    private javax.swing.JButton searchVehicleBtn;
    private javax.swing.JLabel statusLB;
    private javax.swing.JTextField statusTxt;
    private javax.swing.JPanel vehiclePanel;
    private javax.swing.JTable vehicleTable;
    // End of variables declaration//GEN-END:variables

    public void loadComboBox(ConnectionJava connection){
        
        this.brands = new ArrayList<>();
        this.conBrand.getBrands(connection, brands);
        
        for (int i = 0; i < brands.size(); i++) {
            this.brandCBox.addItem(brands.get(i).getBraName());
        }
        
        this.provinces = new ArrayList<>();
        this.conProvince.getProvinces(connection, provinces);
        
        
        for (int i = 0; i < provinces.size(); i++) {
            this.provinceCBox.addItem(provinces.get(i).getProName());
        }
        
    }
    
    public void listVehicles(){
        
        
        
        
    }
}
